### ISSUE TITLE
Crashes when viewing commentaries

### ISSUE THREAD

**Issue by Exzou** [ezra-bible-app/ezra-bible-app#1162]
I'm new to github and have no idea how to set the label to bug. Sorry

Distro:Pop!_OS 22.04 LTS
Kernel:6.9.3-76060903-generic
RAM:24 GB
GPU Driver:4.6 Mesa 24.0.3-1pop1~1711635559~22.04~7a9f319
GPU:AMD Radeon RX 6800 (radeonsi, navi21, LLVM 15.0.7, DRM 3.57, 6.9.3-76060903-generic)
CPU:AMD Ryzen 7 3800X 8-Core

Version info of App:
![image](https://github.com/user-attachments/assets/912990b3-f717-410e-aa6b-f3065dd39d44)

Error report from Terminal:

Computer@computer~$ ezra-bible-app 
Working with userDataPath /home/computer/.config/ezra-bible-app
Using settings file /home/computer/.config/ezra-bible-app/config.json
[18808:1124/174621.483109:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
Using default database dir for database access!
Initializing database at /home/computer/.config/ezra-bible-app
Creating database backup at /home/computer/.config/ezra-bible-app/ezra-backup.sqlite
Working with userDataPath /home/computer/.config/ezra-bible-app
Using settings file /home/computer/.config/ezra-bible-app/html-cache.json
Startup: 2.479s
IpcSettingsHandler: Setting lastUsedVersion to 1.15.0
ERROR: corrupt data during decompression.
[1124/174630.784194:ERROR:elf_dynamic_array_reader.h(64)] tag not found
Segmentation fault (core dumped)

In this screenshot you can see I'm wanting to bring up commentaries. The Application states I need to select a verse, presumably by clicking on the verse. When I click on the verse it crashes after the first verse and recently even the first time. I've uninstalled and reinstalled using `dpkg -i` (no errors) and `apt install` (one permission denied error)
![image](https://github.com/user-attachments/assets/61aa0cb3-38ca-4bc4-acb4-e071f61506ea)
When I click on a verse the first time the app might crash it might not. By the time I click on the second verse it always crashes. I don't see any error messages produced in app when it crashes and I'm only shown the above when launching it from terminal.

**Comment by Exzou** [comment]
@tobias-klein Very welcome. I'll do the best I can to answer your questions.

_"Which commentaries have you installed? Maybe something went wrong during installation?"_ I'm not entirely sure. I went to check and only a few were greyed out. When I check my updates I installed all the ones available in English and the behavior continued.


_"Could you create a zip file of your ~/.sword folder and attach that to the issue or send it to me via email to [contact@ezrabibleapp.net](mailto:)?"_  Email sent.


_"Which distribution package did you install?"_ If I'm understanding your question correctly then it was `ezra-bible-app_ubuntu2204-1.15.0.deb`
![image](https://github.com/user-attachments/assets/aaa1da84-155b-4a98-b22a-c43e0d1d6ad1)

**Comment by tobias-klein** [comment]
@Exzou Thank you for supplying your .sword directory!

Based on running the app off of your .sword directory I could reproduce the issue and find the root cause. The crash was triggered when reading from a module that is locked with an encryption key, in this case the NETnotes. Normally, when installing a module that is locked, the app expects that the key is entered during installation and then tests the key. Either that process did not run correctly or the module was installed by another app without the encryption key being set? Not sure. Either way, based on this root cause I am able to fix this bug by checking the readability of a commentary module before accessing its content.

For now you should be able to work around the problem by uninstalling the NETnotes commentary module.

**Comment by Exzou** [comment]
Thanks! That did the trick. Your assessment that I installed the module via a separate platform is correct.
