### ISSUE TITLE
macOS: Menu not localized

### ISSUE THREAD

**Issue by Berovowilare** [ezra-bible-app/ezra-bible-app#353]
Hello

Die Menüleiste ist noch auf Englisch. 
<img width="631" alt="Bildschirmfoto 2021-06-17 um 20 23 33" src="https://user-images.githubusercontent.com/36891575/122453007-2c53a000-cfaa-11eb-80f5-220bdd807faf.png">

Danke

**Comment by tobias-klein** [comment]
This is a macOS specific bug. This kind of menu only exists on macOS. We must check how this can be solved in the Electron context, because the menu is part of the Electron framework.

**Comment by tobias-klein** [comment]
The only way to do this is to actually populate the menu via the [respective API](https://github.com/electron/electron/blob/v9.3.1/docs/api/menu.md).

[There is a tutorial](https://phrase.com/blog/posts/building-an-electron-app-with-internationalization-i18n/) that shows how to use i18n to localize menu entries.

Since we are not really needing the menu at this point, it may be best to generate an "empty" menu on macOS using the above mentioned API.

**Comment by tobias-klein** [comment]
@augustin-colesnic
The structure in the tutorial is a bit different from what we do, but in principle the approach described there should still work.

We would need to do the following to make this happen:
1) Since the menu integration logic runs in the main process it would need to become part of the "backend" code which is located under /app/backend. I think it could make sense to create a separate folder there.
2) We need to initalize i18next also in the backend - currently it's only used in the frontend. The configuration is in /app/frontend/controllers/i18n_controller.js. We may need to extract the configuration. Or duplicate it. In any case the locale data from /locales must be loaded like in i18n_controller.js - but in the backend instead.
3) Initialize i18next callbacks to menu logic - this must be done in main.js as described in the tutorial.

So ... this is a bit involved requiring some "boiler plate work" first to get i18next running in the backend.

**Comment by augustin-colesnic** [comment]
ok @tobias-klein  
I will give it a try!

Happy new year to all! 🥳

**Comment by augustin-colesnic** [comment]
@tobias-klein  the quickest change to make it only with quit option on the macOS menu si to add in main.js only few lines of code:  `  const menu2 = Menu.buildFromTemplate([{
    label: '&File',
    submenu: [
      {
        label: 'X',
        accelerator: 'Ctrl+Q',
        click: function () {
          app.quit();
        }
      }
    ]
  },])
  Menu.setApplicationMenu(menu2)`  and could look like this:
<img width="1196" alt="Screenshot 2021-12-31 at 14 28 04" src="https://user-images.githubusercontent.com/592416/147823530-5eba6e5b-c4e3-47c2-bcc9-e5cdeb2b7524.png">

This is if we do not care too much about the os menu.

**Comment by tobias-klein** [comment]
Thanks @augustin-colesnic for looking into this one! :)
Yes, we could simply disable large portions of the menu that makes sense.
When I look at the menu from version 1.4.0 I get this:
![Bildschirmfoto 2021-12-31 um 14 59 04](https://user-images.githubusercontent.com/17739895/147827066-84a6154f-523e-41b3-a333-7b731e1c80f9.png)

Not sure where the "Electron" label is coming from in your example, but maybe that's just in development mode and in production it would show "Ezra Bible App".
Does it make sense to keep the option for quitting labeled like in the default menu?
"Quit Ezra Bible App" instead of just the X.

We could then eventually localize that if we successfully integrate i18next.

**Comment by tobias-klein** [comment]
@augustin-colesnic 
In any case ... if you end up adding something in `main.js` - please wrap it conditionally for macOS. Like this:
```JavaScript
if (platformHelper.isMac()) {
  ...
}
```

**Comment by augustin-colesnic** [comment]
Here is how it looks now:

 <img width="272" alt="Screenshot 2022-01-17 at 21 15 00" src="https://user-images.githubusercontent.com/592416/149827261-46aebb92-011a-404b-b3c8-96870c3bf860.png">

**Comment by tobias-klein** [comment]
Thank you @augustin-colesnic
I'll review and merge on the weekend, busy week at work!
