### ISSUE TITLE
Apokrypha?

### ISSUE THREAD

**Issue by Berovowilare** [ezra-bible-app/ezra-bible-app#357]
Hello

I've loaded the KJVA, but I only the the reformed canonical books.
<img width="616" alt="Bildschirmfoto 2021-06-17 um 20 43 50" src="https://user-images.githubusercontent.com/36891575/122455594-d9c7b300-cfac-11eb-9121-cc767f5b1243.png">

**Comment by tobias-klein** [comment]
Yes, this is currently fixed. Adding the apocrypha can certainly be done for those modules that have them. Currently it always shows the whole set of canonical books and greys them out if they are not available. In case of the apocrypha I would rather only show them (maybe as separate column between OT and NT) if they are available and otherwise hide them completely. Does that make sense?

**Comment by Berovowilare** [comment]
Yes that makes sense, but not all has the apocrypha between the OT and the NT. 

Would it be possible to hide the blocks which have no book? For example hide OT if only NT is available. 

Is it possible to grey out the books which are not included? For example: NT and Psalms are availabile. So the blocks OT and NT is appearing but in the OT the non available books are greyed out. 


Thanks

**Comment by tobias-klein** [comment]
> Would it be possible to hide the blocks which have no book? For example hide OT if only NT is available.

I could look into that.

> Is it possible to grey out the books which are not included? For example: NT and Psalms are availabile. So the blocks OT and NT is appearing but in the OT the non available books are greyed out.

It is currently already implemented like this.
