### ISSUE TITLE
Install assistant: Align module info button horizontally in column

### ISSUE THREAD

**Issue by tobias-klein** [ezra-bible-app/ezra-bible-app#396]
I think it would be visually more pleasing if the info button would be vertically aligned (in a column). But I guess to make that happen we would need a table? Or is it possible with pure CSS?
> 
> ![image](https://user-images.githubusercontent.com/17739895/126270117-8911b7cd-dd5a-49a4-b44b-a7b95e02ac77.png)

**Comment by zhuiks** [comment]
I think this is already resolved under #317 wth CSS flexbox:
![Знімок екрану з 2021-07-26 07-38-38](https://user-images.githubusercontent.com/3584119/126990254-3d2298c8-caf8-4f00-98d7-2b2e5a233073.png)
@tobias-klein can you confirm?

**Comment by zhuiks** [comment]
> vertically aligned (in a column)

@tobias-klein Can you explain a little more. Because when I read it initialy under #317 I thought some how "align vertically" = "center" vertically.
And just now I realized that there is a "column".
So for _horizontal_ alignment it would be nice to have info buttons align to the right in the column, is this correct? 
For _vertical_ alignment, probably top versus center would be better. Correct?

**Comment by tobias-klein** [comment]
Maybe my request was a bit misleading.

**Horizontal alignment**
Yes - having the info buttons align to the right of the column would be nice. Currently they are "all over the place".

**Vertical alignment within individual rows**
Yes, top would be better than center.
