### ISSUE TITLE
App does not open in Fedora 36

### ISSUE THREAD

**Issue by FlavioTheoLima** [ezra-bible-app/ezra-bible-app#765]
Hi!
I'm currently using Fedora and when I install the app it installs but doesn't open... I'm missing the lib: libicuio.so.67
Thanks!
God bless everyone!

**Comment by tobias-klein** [comment]
@FlavioTheoLima 
There for the bug report?
Which version of the app and which version of Fedora have you been using?

**Comment by FlavioTheoLima** [comment]
Hi!
Sorry, I didn't provide the system version... It's Fedora 36 and Ezra Bible App 1.6.2

**Comment by tobias-klein** [comment]
We need a package for newer Fedora versions. Right now there are only packages for 31 and 33.

**Comment by tobias-klein** [comment]
@FlavioTheoLima 
I just added support for Fedora 35.
I gave you contributor access so that you can download snapshot builds.
The test package for Fedora 35 can be downloaded [here](https://github.com/ezra-bible-app/ezra-bible-app/suites/8449447623/artifacts/374758999). Could you try that on Fedora 36? (Sometimes library versions don't change in every Fedora release)
If this still does not work I will add a separate package for Fedora 36.

**Comment by FlavioTheoLima** [comment]
Hello my brother!!
Still showing the same error...

![image](https://user-images.githubusercontent.com/104237975/192121261-86c5b596-8855-4841-ba35-f6f747c78d67.png)

**Comment by tobias-klein** [comment]
Could you manually install ICU version 69 by using the following command on a terminal window:

`sudo dnf install libicu69`

**Comment by FlavioTheoLima** [comment]
It worked installing from the terminal... Now I managed to install it on Fedora 36 and I also installed it on Fedora 37 which is in a test version.

**Comment by FlavioTheoLima** [comment]
Installed on Fedora 37 here... It's running pretty stable.

![image](https://user-images.githubusercontent.com/104237975/192142488-2b7c1501-1754-41e9-9f68-e3cdf38361c7.png)

**Comment by tobias-klein** [comment]
Thanks for the feedback! :)
